language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.ivy2
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq curl
  - mkdir -p $HOME/.sbt/launchers/0.13.13/
  - curl -L -o $HOME/.sbt/launchers/0.13.13/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.13/sbt-launch.jar
script:
  - sbt test
matrix:
  fast_finish: true

